### PR TITLE
Add scraper for Rite Aid

### PR DESCRIPTION
**Pull request by Mr0grog**
Why are we scraping Rite Aid? See #474.

This is based on zip code queries for 100 mile radiuses, and keeps a list of the zips that will fairly efficiently cover any state in `sources/riteaid/zip-codes.js`. I calculated these by hand for small states where one or two zips covers them, plus Washington, which is a priority for us. I got some pointers from a friend on calculating an efficient set of zips for larger states, which I'll try and incorporate on a second pass.

### CODE REVIEW

**Comment by Mr0grog** [comment]
OK, I think this is basically good for a deployable first pass.

**Comment by Mr0grog** [comment]
Err, *now* it is.

**Comment by Mr0grog** [comment]
(Rebased after merging #473.)

**Review by astonm — APPROVED** [review]
Tight timeline, I know. Haven't had a chance to review in depth, but from a superficial pass definitely looks shippable.

**Comment by Mr0grog** [comment]
Thanks! 🙏

**Pull request merged**
